apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mini
  name: mini
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mini
    spec:
      containers:
        - env:
            - name: DefaultConnection
              value: >-
                Server=localhost:30002;Database=myapp;User=sa;Password=SA_PASSWORD;MultipleActiveResultSets=true;
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SA_PASSWORD
                  name: sqlserver-secret
          image: gcr.io/devops-282619/github.com/aliomom/miniddd
          imagePullPolicy: IfNotPresent
          name: miniddd
          ports:
            - containerPort: 80
              name: minidddport
              protocol: TCP
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling
  namespace: default
spec:
  maxReplicas: 10
  metrics:
    - resource:
        name: memory
        targetAverageValue: 100Mi
      type: Resource
    - resource:
        name: cpu
        targetAverageUtilization: 50
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mini
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mini
  name: mini-service
  namespace: default
spec:
  clusterIP: 10.31.244.93
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30025
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: mini
  sessionAffinity: None
  type: NodePort
